src/Entity/Agents.php
<?php

namespace App\Entity;

use App\Entity\Specialites;
use App\Repository\AgentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AgentsRepository::class)]
class Agents
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 30)]
    private $nom;

    #[ORM\Column(type: 'string', length: 30)]
    private $prenom;

    #[ORM\Column(type: 'date')]
    private $date_de_naissance;

    #[ORM\ManyToMany(targetEntity: Specialites::class, inversedBy: 'agents')]
    private $specialites;

    #[ORM\OneToOne(inversedBy: 'agents', targetEntity: NomDeCode::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private $nom_de_code;

    #[ORM\ManyToOne(targetEntity: Pays::class, inversedBy: 'agents')]
    #[ORM\JoinColumn(nullable: true)]
    private $nationalite;

    #[ORM\ManyToMany(targetEntity: Missions::class, mappedBy: 'agents')]
    private $missions;

    public function __construct()
    {
        $this->specialites = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

   

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(?\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    /**
     * @return Collection|Specialites[]
     */
    public function getSpecialites(): Collection
    {
        return $this->specialites;
    }

    public function addSpecialite(Specialites $specialite): self
    {
        if (!$this->specialites->contains($specialite)) {
            $this->specialites[] = $specialite;
        }

        return $this;
    }

    public function removeSpecialite(Specialites $specialite): self
    {
        $this->specialites->removeElement($specialite);

        return $this;
    }

    public function getNomDeCode(): ?NomDeCode
    {
        return $this->nom_de_code;
    }

    public function setNomDeCode(NomDeCode $nom_de_code): self
    {
        $this->nom_de_code = $nom_de_code;

        return $this;
    }

    public function getNationalite(): ?Pays
    {
        return $this->nationalite;
    }

    public function setNationalite(?Pays $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Missions[]
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Missions $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions[] = $mission;
            $mission->addAgent($this);
        }

        return $this;
    }

    public function removeMission(Missions $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            $mission->removeAgent($this);
        }

        return $this;
    }
    
    public function getToutesLesSpecialites(): string
    {
        $spe = $this->getSpecialites();
        $text ='';
        if($spe && count($spe) > 0)
        {/**@var $s Specialites */
            foreach($spe as $s)
            {
                if($s)
                {
                    $text =  $text . ' "'.$s.'" ';
                }            
            }
        }else
        {
            return '"Pas de spécialité"';
        } 
        return $text;
    }

    public function getPaysAgent(): mixed
    {
        $pays = $this->getNationalite();
        
        if($pays && strlen($pays) > 0)
        {
         return $pays;
        }else
        {
            return 'Pays Inconnu';
        } 
       
    }
    
    public function __toString()
    {
        return $this->nom_de_code. " (". $this->getPaysAgent(). ", ".  $this->getToutesLesSpecialites() . ")";
    }
}

src/Form/AgentsType.php
<?php

namespace App\Form;

use App\Entity\Agents;
use App\Entity\Pays;
use App\Entity\Specialites;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('agent', PersonType::class, [
            'data_class' => Agents::class,
        ])
            ->add('specialites', EntityType::class, array(
                'class' => Specialites::class,
                'allow_extra_fields' => true,
                'label' => 'Spécialites',
                'expanded' =>true ,
                'multiple'=> true,
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agents::class,
        ]);
    }
}

src/Controller/AgentsController.php
<?php

namespace App\Controller;

use App\Entity\Agents;
use App\Form\AgentsType;
use App\Repository\AgentsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

#[Security("is_granted('ROLE_ADMIN')", statusCode: 404)]
#[Route('/agents')]
class AgentsController extends AbstractController
{
    #[Route('/', name: 'agents_index', methods: ['GET'])]
    public function index(AgentsRepository $agentsRepository): Response
    {
        return $this->render('agents/index.html.twig', [
            'agents' => $agentsRepository->findAll(),
        ]);
    }

    #[Route('/list/{page<\d+>}', name:'agents_index')]
    public function getItemsByPage( AgentsRepository $agentsRepository,int $page = 1): Response
    {
        $query = $agentsRepository  ->createQueryBuilder('i')
                                    ->orderBy('i.nom', 'ASC')
                                    ->getQuery();

        //set page size
        $pageSize = '10';

        // load doctrine Paginator
        $paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($query);

        // you can get total items
        $totalItems = count($paginator);

        // get total pages
        $pageCount = ceil($totalItems / $pageSize);

        // now get one page's items:
        $paginator
            ->getQuery()
            ->setFirstResult($pageSize * ($page-1)) // set the offset
            ->setMaxResults($pageSize); // set the limit

        return $this->render('agents/index.html.twig', [
                'agents' => $paginator,
                'pageCount' => $pageCount
            ]);
    }

    #[Route('/new', name: 'agents_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $agent = new Agents();
        $form = $this->createForm(AgentsType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($agent);
            $entityManager->flush();

            return $this->redirectToRoute('agents_index',array(
            'page' => $page = 1,
            ), Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agents/new.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'agents_show', methods: ['GET'])]
    public function show(Agents $agent): Response
    {
        return $this->render('agents/show.html.twig', [
            'agent' => $agent,
        ]);
    }

    #[Route('/{id}/edit', name: 'agents_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Agents $agent, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AgentsType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('agents_index',array(
            'page' => 1,
            ), Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agents/edit.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'agents_delete', methods: ['POST'])]
    public function delete(Request $request, Agents $agent, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agent->getId(), $request->request->get('_token'))) {
            $entityManager->remove($agent);
            $entityManager->flush();
        }

        return $this->redirectToRoute('agents_index',array(
            'page' => 1,
            ), Response::HTTP_SEE_OTHER);
    }
}

templates/agents/_delete_form.html.twig
<form method="post" action="{{ path('agents_delete', {'id': agent.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agent.id) }}">
    <button class="btn inlineForm">Supprimer</button>
</form>

templates/agents/_form.html.twig
{{ form_start(form) }} <button class="btn btn-success inlineForm">{{ button_label|default('Enregistrer') }}</button>
 <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>
      {{ form_row(form.agent) }}
  

   {{ form_label(form.specialites) }} 
        <div class="list">
            {% for field in form.specialites %}
                <div class="checkbox-list">
                    {{ form_widget(field) }}
                    {{ form_label(field) }}
                </div>
            {% endfor %}
        </div>  
{{ form_end(form) }}

templates/agents/edit.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Edit Agents{% endblock %}

{% block main %}

    <h1>Edit Agents</h1>
  <a type="button" class="btn inlineForm" href="{{ path('agents_index', {'page': 1})  }}">Retour</a>
  
  {{ include('agents/_delete_form.html.twig') }}
  
  {{ include('agents/_form.html.twig', {'button_label': 'Enregistrer'}) }}
  
{% endblock %}

templates/agents/index.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Agents{% endblock %}

{% block main %}
    <h1>Agents</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Nom de code</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Date de naissance</th>
                <th>Spécialités</th>
                <th>Pays</th>
                <th>Voir/Modifier</th>
            </tr>
        </thead>
        <tbody>
        {% for agent in agents %}
            <tr>
                <td>{{ agent.getNomDeCode.code }}</td>
                <td>{{ agent.nom }}</td>
                <td>{{ agent.prenom }}</td>
                <td>{{ agent.dateDeNaissance ? agent.dateDeNaissance|date('d/m/Y') : '' }}</td>
                <td> {% for specialites_id in agent.getSpecialites %}-{{specialites_id|spaceless }}<br>{% endfor %}</td>
                <td>{{ agent.nationalite }}</td>
                <td>
                    <a type="button" class="btn btn-primary" href="{{ path('agents_show', {'id': agent.id}) }}">Voir</a>
                    <a type="button" class="btn btn-primary" href="{{ path('agents_edit', {'id': agent.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if pageCount  is defined and pageCount  > 1 %}
        {% for i in 1..pageCount %}
            <a type="button" class="btn paging" href="/agents/list/{{ i }}">{{ i }}</a>
         {% endfor %}
         {% endif %}
         <br>
    <a type="button" class="btn btn-primary" href="{{ path('agents_new') }}">Ajouter </a>
{% endblock %}

templates/agents/new.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Ajouter  Agents{% endblock %}

{% block main %}

    <h1>Ajouter Agents</h1>
 <a type="button" class="btn" href="{{ path('agents_index', {'page': 1}) }}">Retour</a>
    {{ include('agents/_form.html.twig') }}

   
{% endblock %}

templates/agents/show.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Agents{% endblock %}

{% block main %}
    <h1>Agents</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ agent.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ agent.prenom }}</td>
            </tr>
            <tr>
                <th>Date de naissance</th>
                <td>{{ agent.dateDeNaissance ? agent.dateDeNaissance|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Nom De Code</th>
                <td>{{ agent.getNomDeCode.code }}</td>
            </tr>
            <tr>
                <th>Spécialités</th>
                <td> {% for specialites_id in agent.getSpecialites %}-{{specialites_id|spaceless }}<br>{% endfor %}</td>
            </tr>
            <tr>
                <th>Pays d'origine</th>
                <td>{{ agent.nationalite }}</td>
            </tr>
        </tbody>
    </table>

    <a type="button" class="btn" href="{{ path('agents_index', {'page': 1}) }}">Retour</a>

    <a type="button" class="btn" href="{{ path('agents_edit', {'id': agent.id}) }}">Modifier</a>

    {{ include('agents/_delete_form.html.twig') }}
{% endblock %}