src/Entity/Missions.php
<?php

namespace App\Entity;

use App\Repository\MissionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Validator\MissionPlanques as MissionPlanques;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: MissionsRepository::class)]
class Missions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\OneToOne(inversedBy: 'missions', targetEntity: NomDeCode::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private $nom_de_code;

    #[ORM\ManyToOne(targetEntity: Pays::class, inversedBy: 'missions',fetch: 'EXTRA_LAZY')]
    #[ORM\JoinColumn(nullable: false)]
    private $pays;
    
    #[ORM\ManyToMany(targetEntity: Agents::class, inversedBy: 'missions')]
    private $agents;

    #[ORM\ManyToMany(targetEntity: Contacts::class, inversedBy: 'missions')]
    private $contacts;

    #[ORM\ManyToMany(targetEntity: Cibles::class, inversedBy: 'missions')]
    private $Cibles;

    #[ORM\ManyToOne(targetEntity: TypeDeMissions::class, inversedBy: 'missions')]
    #[ORM\JoinColumn(nullable: false)]
    private $type;

    #[ORM\ManyToOne(targetEntity: Status::class, inversedBy: 'missions')]
    #[ORM\JoinColumn(nullable: false)]
    private $statut;

    #[ORM\ManyToMany(targetEntity: Planques::class, inversedBy: 'missions', cascade: ["persist","remove"],fetch: 'EXTRA_LAZY')]
    #[ORM\JoinColumn(nullable: true)]
    private $planques;

    #[ORM\ManyToOne(targetEntity: Specialites::class, inversedBy: 'missions')]
    #[ORM\JoinColumn(nullable: false)]
    private $specialite;

    #[ORM\Column(type: 'date')]
    private $date_debut;

    #[ORM\Column(type: 'date', nullable: true)]
    private $date_fin;




    public function __construct()
    {
        $this->agents = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->Cibles = new ArrayCollection();
        $this->planques = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNomDeCode(): ?NomDeCode
    {
        return $this->nom_de_code;
    }

    public function setNomDeCode(NomDeCode $nom_de_code): self
    {
        $this->nom_de_code = $nom_de_code;

        return $this;
    }

    public function getPays(): ?Pays
    {
        return $this->pays;
    }

    public function setPays(?Pays $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * @return Collection|Agents[]
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agents $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents[] = $agent;
        }

        return $this;
    }

    public function removeAgent(Agents $agent): self
    {
        $this->agents->removeElement($agent);

        return $this;
    }

    /**
     * @return Collection|Contacts[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contacts $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
        }

        return $this;
    }

    public function removeContact(Contacts $contact): self
    {
        $this->contacts->removeElement($contact);

        return $this;
    }

    /**
     * @return Collection|Cibles[]
     */
    public function getCibles(): Collection
    {
        return $this->Cibles;
    }

    public function addCible(Cibles $cible): self
    {
        if (!$this->Cibles->contains($cible)) {
            $this->Cibles[] = $cible;
        }

        return $this;
    }

    public function removeCible(Cibles $cible): self
    {
        $this->Cibles->removeElement($cible);

        return $this;
    }

    public function getType(): ?TypeDeMissions
    {
        return $this->type;
    }

    public function setType(?TypeDeMissions $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStatut(): ?Status
    {
        return $this->statut;
    }

    public function setStatut(?Status $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @return Collection|Planques[]
     */
    public function getPlanques(): Collection
    {
        return $this->planques;
    }

    public function addPlanque(Planques $planque): self
    {
        if (!$this->planques->contains($planque)) {
            $this->planques[] = $planque;
           
        }

        return $this;
    }

    public function removePlanque(Planques $planque): self
    {
        $this->planques->removeElement($planque);

        return $this;
    }
    

    public function getSpecialite(): ?Specialites
    {
        return $this->specialite;
    }

    public function setSpecialite(?Specialites $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }
    
    public function __toString()
    {
        return $this->titre;
    }


    
}

src/Form/MissionsType.php
<?php

namespace App\Form;

use App\Entity\Agents;
use App\Entity\Cibles;
use App\Entity\Contacts;
use App\Entity\Missions;
use App\Entity\Pays;
use App\Entity\Planques;
use App\Entity\Specialites;
use App\Repository\PlanquesRepository;
use App\Validator\CiblesAgents;
use App\Validator\ContactsPays;
use App\Validator\MissionPlanques;
use App\Validator\UnAgentAvecLaSpecialiteDeMission;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MissionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        
        $builder
            ->add('titre')
            ->add('description')
            ->add('date_debut', DateType::class, [
                'data' =>  new \DateTime("now"),
                'attr' => ['class' => 'inlineForm'],
            ])
            ->add('date_fin', DateType::class, [
                'data' =>  new \DateTime("now"),
                'attr' => ['class' => 'inlineForm'],
            ])
            ->add('nom_de_code', NomDeCodeAjouter::class, [
                'attr' => ['class' => 'inlineForm'],
                'label' => false
            ])
            ->add('type')
            ->add('statut')
            ->add('specialite', EntityType::class, [ 
                'class' => Specialites::class,
                'constraints' => new UnAgentAvecLaSpecialiteDeMission(),
            ]) 
            ->add('pays', EntityType::class, [ 
                'class' => Pays::class,
                'constraints' => [new CiblesAgents(),new ContactsPays(),new MissionPlanques()],
            ])
            ->add('planques', EntityType::class, array(
                'class' => Planques::class,
                'allow_extra_fields' => true,
                'label' => 'Planques',
                'expanded' =>true ,
                'multiple'=> true,
            ))
            ->add('contacts', EntityType::class, array(
                'class' => Contacts::class,
                'allow_extra_fields' => true,
                'label' => 'Contacts',
                'expanded' =>true ,
                'multiple'=> true,
            ))
            ->add('agents', EntityType::class, array(
                'class' => Agents::class,
                'allow_extra_fields' => true,
                'label' => 'Agents',
                'expanded' =>true ,
                'multiple'=> true,
            ))
            ->add('Cibles', EntityType::class, array(
                'class' => Cibles::class,
                'allow_extra_fields' => true,
                'label' => 'Cibles',
                'expanded' =>true ,
                'multiple'=> true,
            ))
        ;
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Missions::class,
        ]);
    }
}

src/Controller/MissionsController.php
<?php

namespace App\Controller;

use App\Entity\Missions;
use App\Form\MissionsType;
use App\Repository\MissionsRepository;
use App\Validator\CiblesAgents;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

#[Route('/missions')]
class MissionsController extends AbstractController
{
    #[Route('/', name: 'missions_index', methods: ['GET'])]
    public function index(MissionsRepository $missionsRepository): Response
    {
        return $this->render('missions/index.html.twig', [
            'missions' => $missionsRepository->findAll(),
        ]);
    }
    
    #[Route('/list/{page}', name:'missions_index')]
    public function getItemsByPage(MissionsRepository $missionsRepository,int $page = 1): Response
    {
        $query = $missionsRepository    ->createQueryBuilder('i')
                                        ->orderBy('i.titre', 'ASC')
                                        ->getQuery();

        //set page size
        $pageSize = '10';

        // load doctrine Paginator
        $paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($query);

        // you can get total items
        $totalItems = count($paginator);

        // get total pages
        $pageCount = ceil($totalItems / $pageSize);

        // now get one page's items:
        $paginator
            ->getQuery()
            ->setFirstResult($pageSize * ($page-1)) // set the offset
            ->setMaxResults($pageSize); // set the limit

        return $this->render('missions/index.html.twig', [
                'missions' => $paginator,
                'pageCount' => $pageCount
            ]);
    }
    #[Security("is_granted('ROLE_ADMIN')", statusCode: 404)]
    #[Route('/new', name: 'missions_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    { 
        $mission = new Missions();
        $form = $this->createForm(MissionsType::class, $mission,[
           // 'validation_groups' => ['CiblesAgents','ContactsPays']
           // 'constraints' => new CiblesAgents(),
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($mission);
            $entityManager->flush();
           
            return $this->redirectToRoute('missions_index',array(
                'page' => 1,
                ),  Response::HTTP_SEE_OTHER);
                
        }

        return $this->renderForm('missions/new.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'missions_show', methods: ['GET'])]
    public function show(Missions $mission): Response
    {
        return $this->render('missions/show.html.twig', [
            'mission' => $mission,
        ]);
    }

    #[Security("is_granted('ROLE_ADMIN')", statusCode: 404)]
    #[Route('/{id}/edit', name: 'missions_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Missions $mission, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MissionsType::class, $mission,[
            //'validation_groups' => ['CiblesAgents','ContactsPays']
           // 'constraints' => new CiblesAgents(),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $entityManager->flush();

            return $this->redirectToRoute('missions_index',array(
                'page' => $page = 1,
                ), Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('missions/edit.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    #[Security("is_granted('ROLE_ADMIN')", statusCode: 404)]
    #[Route('/{id}', name: 'missions_delete', methods: ['POST'])]
    public function delete(Request $request, Missions $mission, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mission->getId(), $request->request->get('_token'))) {
            $entityManager->remove($mission);
            $entityManager->flush();
        }
        return $this->redirectToRoute('missions_index',array(
            'page' => $page = 1,
            ), Response::HTTP_SEE_OTHER);
    }

}

templates/missions/_delete_form.html.twig
<form method="post" action="{{ path('missions_delete', {'id': mission.id}) }}" onsubmit="return confirm('Are you sure you want to delete {{ mission.titre }}?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission.id) }}">
    <button class="btn">Supprimer</a></button>
</form>

templates/missions/_form.html.twig
{{ form_start(form) }}
    <button class="btn btn-success inlineForm">{{ button_label|default('Enregistrer') }}</button>
      {{ form_row(form.titre) }}
    {{ form_row(form.description) }}
    {{ form_row(form.date_debut) }}
    
    {{ form_row(form.date_fin) }}
    {{ form_row(form.nom_de_code) }}
    {{ form_row(form.type) }}
    {{ form_row(form.statut) }}
    {{ form_row(form.specialite) }}
    {{ form_row(form.pays) }}

    {{ form_label(form.planques) }} 
        <div class="list">
            {% for field in form.planques %}
                <div class="checkbox-list">
                    {{ form_widget(field) }}
                    {{ form_label(field) }}
                </div>
            {% endfor %}
        </div>
    {{ form_label(form.agents) }} 
        <div class="list long">
            {% for field in form.agents %}
                <div class="checkbox-list">
                    {{ form_widget(field) }}
                    {{ form_label(field) }}
                </div>
            {% endfor %}
        </div>
    {{ form_label(form.contacts) }} 
        <div class="list">
            {% for field in form.contacts %}
                <div class="checkbox-list">
                    {{ form_widget(field) }}
                    {{ form_label(field) }}
                </div>
            {% endfor %}
        </div>
    {{ form_label(form.Cibles) }} 
        <div class="list">
            {% for field in form.Cibles %}
                <div class="checkbox-list">
                    {{ form_widget(field) }}
                    {{ form_label(field) }}
                </div>
            {% endfor %}
        </div>
    
{{ form_end(form) }}

templates/missions/edit.html.twig
{% extends 'welcome.html.twig' %}
{% block title %}Edit Missions{% endblock %}

{% block main %}
    <h1>Edit Missions</h1>
    <a type="button" class="btn" href="{{ path('missions_index', {'page': 1})  }}">Retour</a>
    {{ include('missions/_delete_form.html.twig') }}
    {{ include('missions/_form.html.twig', {'button_label': 'Enregistrer'}) }}
{% endblock %}

templates/missions/index.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Missions index{% endblock %}

{% block main %}
    <h1>Missions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Specialité requise</th>
                <th>Agents affectés</th>
                {% if app.user %}
                <th>Voir/Modifier</th>
                {% else %}
                 <th>Voir</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for mission in missions %}
            <tr>
                <td>{{ mission.titre }}</td>
                <td>{{ mission.description }}</td>
                <td>{{ mission.dateDebut ? mission.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ mission.dateFin ? mission.dateFin|date('Y-m-d') : '' }}</td>
                 <td>{{ mission.specialite }}</td>
                 <td> {% for agent in mission.getAgents %}-{{agent|spaceless }}<br>{% endfor %}</td>
                <td>
                    <a type="button" class="btn" href="{{ path('missions_show', {'id': mission.id}) }}">Voir</a>
                     {% if app.user %}
                    <a type="button" class="btn" href="{{ path('missions_edit', {'id': mission.id}) }}">Modifier</a>
                     {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
 {% if pageCount  is defined and pageCount  > 1 %}
        {% for i in 1..pageCount %}
            <a type="button" class="btn paging" href="/missions/list/{{ i }}">{{ i }}</a>
         {% endfor %}
         {% endif %}
         <br>
    <a type="button" class="btn" href="{{ path('missions_new') }}">Ajouter </a>
{% endblock %}

templates/missions/new.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Ajouter  Missions{% endblock %}

{% block main %}
    <h1>Ajouter Missions</h1>
    <a type="button" class="btn" href="/missions/list/1">Retour</a>
    {{ include('missions/_form.html.twig') }}
{% endblock %}

templates/missions/show.html.twig
{% extends 'welcome.html.twig' %}

{% block title %}Missions{% endblock %}

{% block main %}
    <h1>Missions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mission.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ mission.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ mission.description }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ mission.dateDebut ? mission.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ mission.dateFin ? mission.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Planques</th>
                <td> 
                    {% for planques in mission.planques %}
                        {{ planques.code }}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Spécialité nécessaire</th>
                <td>{{ mission.specialite }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ mission.pays }}</td>
            </tr>
            <tr>
                <th>Agents</th>
                <td> 
                    {% for agents in mission.agents %}
                        {{ agents.nom }}
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a type="button" class="btn" href="{{ path('missions_index', {'page': 1})  }}">Retour</a>

    <a type="button" class="btn" href="{{ path('missions_edit', {'id': mission.id}) }}">Modifier</a>

    {{ include('missions/_delete_form.html.twig') }}
{% endblock %}